targets:
  $default:
    builders:
      finamp:finamp_settings_generator:
        enabled: true
      finamp:searchable_generator:
        enabled: true
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - deprecated_member_use_from_same_package
          preamble: |
            // dart format off
      flutter_gen_runner:
        options:
          line_length: 120

builders:
  finamp_settings_generator:
    import: "package:finamp/builders/finamp_settings_builder.dart"
    builder_factories: ["getFinampSettingsGenerator"]
    build_extensions: { ".dart": ["finamp_settings_generator.g.part"] }
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  searchable_generator: # ADD THIS BLOCK
    import: "package:finamp/builders/searchable_builder.dart"
    builder_factories: ["getSearchableGenerator"]
    build_extensions: { ".dart": ["searchable_generator.g.part"] }
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
