#!/usr/bin/env bash
# Build sideload installers for Android (APK) and iOS (development IPA).
# Paste on: Dev MacBook, from the Finamp repo root (or anywhere; script cd's to root).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DIST_DIR="${DIST_DIR:-$ROOT/dist}"
ANDROID_MODE="${ANDROID_MODE:-debug}" # debug | release
IOS_TEAM_ID="${IOS_TEAM_ID:-F3E25E64U6}"
IOS_BUNDLE_ID="${IOS_BUNDLE_ID:-com.anonymous.finamp}"
SKIP_IOS="${SKIP_IOS:-0}"
SKIP_ANDROID="${SKIP_ANDROID:-0}"

export ANDROID_HOME="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-$ANDROID_HOME}"
# Gradle 7.6 (this project) needs Java <= 19. Prefer Homebrew OpenJDK 17.
if [[ -z "${JAVA_HOME:-}" ]]; then
  if [[ -x "/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home/bin/java" ]]; then
    export JAVA_HOME="/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"
  elif [[ -x "/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home/bin/java" ]]; then
    export JAVA_HOME="/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"
  elif /usr/libexec/java_home -v 17 >/dev/null 2>&1; then
    export JAVA_HOME="$(/usr/libexec/java_home -v 17)"
  elif [[ -x "/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java" ]]; then
    export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
  elif /usr/libexec/java_home >/dev/null 2>&1; then
    export JAVA_HOME="$(/usr/libexec/java_home)"
  fi
fi
export PATH="${JAVA_HOME:+$JAVA_HOME/bin:}$ANDROID_HOME/platform-tools:$PATH"
echo "==> JAVA_HOME=$JAVA_HOME ($("$JAVA_HOME/bin/java" -version 2>&1 | head -1))"
# Prefer this JDK for Flutter tooling and Gradle without committing a machine path
flutter config --jdk-dir="$JAVA_HOME" >/dev/null
mkdir -p "$HOME/.gradle"
USER_GP="$HOME/.gradle/gradle.properties"
touch "$USER_GP"
if grep -q '^org.gradle.java.home=' "$USER_GP" 2>/dev/null; then
  # portable in-place replace for macOS sed
  sed -i.bak "s|^org.gradle.java.home=.*|org.gradle.java.home=$JAVA_HOME|" "$USER_GP"
  rm -f "${USER_GP}.bak"
else
  echo "org.gradle.java.home=$JAVA_HOME" >>"$USER_GP"
fi

mkdir -p "$DIST_DIR"

echo "==> Flutter $(flutter --version 2>/dev/null | head -1)"
flutter pub get

ensure_android_keystore() {
  local keystore="$ROOT/android/upload-keystore.jks"
  local props="$ROOT/android/key.properties"
  if [[ -f "$props" && -f "$keystore" ]]; then
    echo "==> Android keystore already present"
    return
  fi
  echo "==> Generating local Android upload keystore (gitignored)"
  keytool -genkey -v \
    -keystore "$keystore" \
    -storetype JKS \
    -keyalg RSA \
    -keysize 2048 \
    -validity 10000 \
    -alias upload \
    -storepass finamp-local \
    -keypass finamp-local \
    -dname "CN=Finamp Local, OU=Dev, O=Brian Perkins, L=Local, ST=NA, C=US" \
    >/dev/null
  cat >"$props" <<EOF
storePassword=finamp-local
keyPassword=finamp-local
keyAlias=upload
storeFile=upload-keystore.jks
EOF
  echo "    Wrote android/key.properties + android/upload-keystore.jks"
}

build_android() {
  local out
  if [[ "$ANDROID_MODE" == "release" ]]; then
    ensure_android_keystore
    echo "==> Building Android release APK"
    flutter build apk --release
    out="$ROOT/build/app/outputs/flutter-apk/app-release.apk"
    cp -f "$out" "$DIST_DIR/finamp-android-release.apk"
    echo "✓ Android release APK: $DIST_DIR/finamp-android-release.apk"
    echo "  Note: same applicationId as store Finamp — uninstall store build first if install fails."
  else
    echo "==> Building Android debug APK (applicationId …finamp.debug — installs alongside store)"
    flutter build apk --debug
    out="$ROOT/build/app/outputs/flutter-apk/app-debug.apk"
    cp -f "$out" "$DIST_DIR/finamp-android-debug.apk"
    echo "✓ Android debug APK: $DIST_DIR/finamp-android-debug.apk"
  fi
}

write_ios_local_xcconfig() {
  local local_cfg="$ROOT/ios/Flutter/Local.xcconfig"
  # Only set DEVELOPMENT_TEAM here. Do NOT set PRODUCT_BUNDLE_IDENTIFIER in an
  # xcconfig/command-line override — that stamps CocoaPods frameworks with the
  # same id and iOS rejects install (DuplicateIdentifier / "Unable to Install").
  cat >"$local_cfg" <<EOF
// Generated by scripts/build-mobile-installers.sh — gitignored
DEVELOPMENT_TEAM=$IOS_TEAM_ID
EOF
  echo "==> Wrote ios/Flutter/Local.xcconfig (team=$IOS_TEAM_ID)"
}

build_ios() {
  write_ios_local_xcconfig
  echo "==> Building iOS development IPA (Apple Development signing)"
  local pb="$ROOT/ios/Runner.xcodeproj/project.pbxproj"
  local pb_bak="$pb.installer.bak"
  cp -f "$pb" "$pb_bak"
  # Patch Runner target only (pbxproj entries). Never pass PRODUCT_BUNDLE_IDENTIFIER
  # as an xcodebuild KEY=VALUE — that overrides every Pods framework too.
  sed -i '' \
    -e "s/DEVELOPMENT_TEAM = PFNS8PTRM7;/DEVELOPMENT_TEAM = $IOS_TEAM_ID;/g" \
    -e "s/PRODUCT_BUNDLE_IDENTIFIER = \"com.unicornsonlsd.finamp-ios\";/PRODUCT_BUNDLE_IDENTIFIER = \"$IOS_BUNDLE_ID\";/g" \
    "$pb"
  echo "    Patched Runner pbxproj → team=$IOS_TEAM_ID bundle=$IOS_BUNDLE_ID"

  local archive_path="$ROOT/build/ios/archive/Runner.xcarchive"
  local export_path="$ROOT/build/ios/ipa"
  local export_plist
  export_plist="$(mktemp -t finamp-export).plist"
  cat >"$export_plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>development</string>
	<key>teamID</key>
	<string>$IOS_TEAM_ID</string>
	<key>signingStyle</key>
	<string>automatic</string>
	<key>compileBitcode</key>
	<false/>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>signingCertificate</key>
	<string>Apple Development</string>
</dict>
</plist>
EOF

  local build_ok=0
  (
    set -e
    # Prepare Flutter iOS build pieces without signing via flutter (avoids missing -allowProvisioningUpdates)
    flutter build ios --config-only --release
    cd "$ROOT/ios"
    pod install
    rm -rf "$archive_path" "$export_path"
    mkdir -p "$(dirname "$archive_path")" "$export_path"
    xcodebuild \
      -workspace Runner.xcworkspace \
      -scheme Runner \
      -configuration Release \
      -destination 'generic/platform=iOS' \
      -archivePath "$archive_path" \
      DEVELOPMENT_TEAM="$IOS_TEAM_ID" \
      CODE_SIGN_STYLE=Automatic \
      -allowProvisioningUpdates \
      -allowProvisioningDeviceRegistration \
      archive
    xcodebuild \
      -exportArchive \
      -archivePath "$archive_path" \
      -exportOptionsPlist "$export_plist" \
      -exportPath "$export_path" \
      -allowProvisioningUpdates \
      -allowProvisioningDeviceRegistration
  ) && build_ok=1

  mv -f "$pb_bak" "$pb"
  rm -f "$export_plist"
  echo "    Restored upstream pbxproj signing settings"

  if [[ "$build_ok" -eq 1 ]]; then
    local ipa
    ipa="$(find "$export_path" -name '*.ipa' -type f | head -1)"
    if [[ -n "$ipa" ]]; then
      cp -f "$ipa" "$DIST_DIR/finamp-ios-development.ipa"
      echo "✓ iOS IPA: $DIST_DIR/finamp-ios-development.ipa"
    else
      echo "✗ Archive exported but no .ipa under $export_path"
      exit 1
    fi
  else
    echo "⚠ iOS IPA build failed."
    echo "  Common causes:"
    echo "    • Xcode not signed in (error: missing Xcode-Token / No Accounts)"
    echo "      → Xcode → Settings → Accounts → add perkinsfam.bp@gmail.com"
    echo "    • iPhone not registered to the personal team yet"
    echo "      → USB-connect iPhone XS once, trust this Mac, open the workspace in Xcode"
    echo
    echo "  Then re-run:"
    echo "    open \"$ROOT/ios/Runner.xcworkspace\""
    echo "    # Signing & Capabilities → Team: Brian Perkins ($IOS_TEAM_ID)"
    echo "    # Bundle Identifier: $IOS_BUNDLE_ID"
    echo "    SKIP_ANDROID=1 ./scripts/build-mobile-installers.sh"
    echo "  Or install live: flutter run --release -d <device-id>"
    echo "  Docs: docs/MOBILE_INSTALLERS.md"
    exit 1
  fi
}

install_android_hint() {
  cat <<EOF

--- Install Android (Pixel / any device) ---
# USB debugging on, then on Dev MacBook:
adb install -r "$DIST_DIR/finamp-android-${ANDROID_MODE}.apk"

# Or copy the APK to the phone and open it (allow unknown sources).
EOF
}

install_ios_hint() {
  cat <<EOF

--- Install iOS (iPhone) ---
Do NOT copy the .ipa via Finder and tap it — development IPAs will show
"Unable to Install Finamp / Please try again later."

Day-to-day Profile (in-place, keeps Trust):
  ./scripts/install-ios-profile.sh

Do NOT use: flutter install   # uninstalls first; wipes personal-team Trust

IPA (USB-connected), on Dev MacBook:
1. Xcode → Window → Devices and Simulators → select iPhone → (+) under Installed Apps
   → choose: $DIST_DIR/finamp-ios-development.ipa
   OR in-place (preferred over uninstall):
   TMP=\$(mktemp -d) && unzip -q "$DIST_DIR/finamp-ios-development.ipa" -d "\$TMP" \\
     && xcrun devicectl device install app --device 00008020-0004484921F0002E "\$TMP/Payload/Runner.app"
2. On iPhone: Settings → General → VPN & Device Management → trust your developer certificate
   once, then leave at least one app from this personal team installed.
EOF
}

[[ "$SKIP_ANDROID" == "1" ]] || build_android
[[ "$SKIP_IOS" == "1" ]] || build_ios

echo
echo "==> Artifacts in $DIST_DIR"
ls -lh "$DIST_DIR" || true
[[ "$SKIP_ANDROID" == "1" ]] || install_android_hint
[[ "$SKIP_IOS" == "1" ]] || install_ios_hint
echo
echo "OK: mobile installer build finished"
