#!/usr/bin/env bash
# Build Profile APK + IPA, write latest.json / SideStore source, publish to GitHub
# Releases (version tag + floating sideload-latest).
#
# Paste on: Dev MacBook, from the Finamp repo root.
#
# Versioning: pubspec `X.Y.Z-sideload.N+build` (integer build compared for OTA).
# Keystore: android/upload-keystore.jks + android/key.properties (gitignored).
# Backup keystore in Bitwarden: "Finamp sideload Android keystore".
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DIST_DIR="${DIST_DIR:-$ROOT/dist}"
REPO="${GITHUB_REPO:-itdir/finamp}"
FLOATING_TAG="${FLOATING_TAG:-sideload-latest}"
IOS_TEAM_ID="${IOS_TEAM_ID:-F3E25E64U6}"
IOS_BUNDLE_ID="${IOS_BUNDLE_ID:-com.anonymous.finamp}"
SKIP_IOS="${SKIP_IOS:-0}"
SKIP_ANDROID="${SKIP_ANDROID:-0}"
SKIP_UPLOAD="${SKIP_UPLOAD:-0}"
NOTES="${NOTES:-}"

export ANDROID_HOME="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-$ANDROID_HOME}"
if [[ -z "${JAVA_HOME:-}" ]]; then
  if [[ -x "/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home/bin/java" ]]; then
    export JAVA_HOME="/usr/local/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"
  elif [[ -x "/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home/bin/java" ]]; then
    export JAVA_HOME="/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"
  elif /usr/libexec/java_home -v 17 >/dev/null 2>&1; then
    export JAVA_HOME="$(/usr/libexec/java_home -v 17)"
  fi
fi
export PATH="${JAVA_HOME:+$JAVA_HOME/bin:}$ANDROID_HOME/platform-tools:$PATH"

mkdir -p "$DIST_DIR"
flutter pub get

ensure_android_keystore() {
  local keystore="$ROOT/android/upload-keystore.jks"
  local props="$ROOT/android/key.properties"
  if [[ -f "$props" && -f "$keystore" ]]; then
    echo "==> Android keystore already present"
    return
  fi
  echo "==> Generating sideload Android upload keystore (gitignored)"
  echo "    Back up to Bitwarden Secure Note: Finamp sideload Android keystore"
  keytool -genkey -v \
    -keystore "$keystore" \
    -storetype JKS \
    -keyalg RSA \
    -keysize 2048 \
    -validity 10000 \
    -alias upload \
    -storepass finamp-local \
    -keypass finamp-local \
    -dname "CN=Finamp Sideload, OU=Dev, O=Brian Perkins, L=Local, ST=NA, C=US" \
    >/dev/null
  cat >"$props" <<EOF
storePassword=finamp-local
keyPassword=finamp-local
keyAlias=upload
storeFile=../upload-keystore.jks
EOF
  echo "    Wrote android/key.properties + android/upload-keystore.jks"
}

sha256_file() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    sha256sum "$1" | awk '{print $1}'
  fi
}

parse_pubspec_version() {
  local line
  line="$(grep -E '^version:' "$ROOT/pubspec.yaml" | head -1 | sed 's/^version:[[:space:]]*//')"
  # Expect: 0.9.25-sideload.1+127 or 0.9.25+126
  VERSION_NAME="${line%%+*}"
  VERSION_BUILD="${line##*+}"
  if [[ "$VERSION_NAME" == "$line" || -z "$VERSION_BUILD" ]]; then
    echo "✗ pubspec version must be name+build (got: $line)" >&2
    exit 1
  fi
  if [[ "$VERSION_NAME" =~ ^([0-9]+\.[0-9]+\.[0-9]+) ]]; then
    UPSTREAM_VERSION="${BASH_REMATCH[1]}"
  else
    UPSTREAM_VERSION="$VERSION_NAME"
  fi
  GIT_TAG="v${VERSION_NAME}+${VERSION_BUILD}"
  echo "==> Version name=$VERSION_NAME build=$VERSION_BUILD upstream=$UPSTREAM_VERSION tag=$GIT_TAG"
}

bump_sideload() {
  # Optional: BUMP=1 ./scripts/publish-sideload-release.sh
  # Increments -sideload.N and +build while keeping upstream X.Y.Z.
  parse_pubspec_version
  local base rev new_rev new_build new_name
  if [[ "$VERSION_NAME" =~ ^([0-9]+\.[0-9]+\.[0-9]+)-sideload\.([0-9]+)$ ]]; then
    base="${BASH_REMATCH[1]}"
    rev="${BASH_REMATCH[2]}"
  elif [[ "$VERSION_NAME" =~ ^([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
    base="${BASH_REMATCH[1]}"
    rev=0
  else
    echo "✗ Cannot bump version name: $VERSION_NAME" >&2
    exit 1
  fi
  new_rev=$((rev + 1))
  new_build=$((VERSION_BUILD + 1))
  new_name="${base}-sideload.${new_rev}"
  sed -i.bak -E "s/^version:.*/version: ${new_name}+${new_build}/" "$ROOT/pubspec.yaml"
  rm -f "$ROOT/pubspec.yaml.bak"
  echo "==> Bumped pubspec to ${new_name}+${new_build}"
}

build_android_profile() {
  ensure_android_keystore
  echo "==> Building Android profile APK (applicationId …finamp.profile)"
  flutter build apk --profile
  local out="$ROOT/build/app/outputs/flutter-apk/app-profile.apk"
  cp -f "$out" "$DIST_DIR/finamp-android-profile.apk"
  echo "✓ $DIST_DIR/finamp-android-profile.apk"
}

build_ios_profile() {
  echo "==> Building iOS Profile IPA (personal team)"
  local local_cfg="$ROOT/ios/Flutter/Local.xcconfig"
  cat >"$local_cfg" <<EOF
// Generated by publish-sideload-release.sh — gitignored
DEVELOPMENT_TEAM=$IOS_TEAM_ID
EOF
  local pb="$ROOT/ios/Runner.xcodeproj/project.pbxproj"
  local pb_bak="$pb.publish.bak"
  cp -f "$pb" "$pb_bak"
  sed -i '' \
    -e "s/DEVELOPMENT_TEAM = PFNS8PTRM7;/DEVELOPMENT_TEAM = $IOS_TEAM_ID;/g" \
    -e "s/PRODUCT_BUNDLE_IDENTIFIER = \"com.unicornsonlsd.finamp-ios\";/PRODUCT_BUNDLE_IDENTIFIER = \"$IOS_BUNDLE_ID\";/g" \
    "$pb"

  local archive_path="$ROOT/build/ios/archive/Runner.xcarchive"
  local export_path="$ROOT/build/ios/ipa"
  local export_plist
  export_plist="$(mktemp -t finamp-export).plist"
  cat >"$export_plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>development</string>
	<key>teamID</key>
	<string>$IOS_TEAM_ID</string>
	<key>signingStyle</key>
	<string>automatic</string>
	<key>compileBitcode</key>
	<false/>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>signingCertificate</key>
	<string>Apple Development</string>
</dict>
</plist>
EOF

  local build_ok=0
  (
    set -e
    flutter build ios --config-only --profile
    cd "$ROOT/ios"
    pod install
    rm -rf "$archive_path" "$export_path"
    mkdir -p "$(dirname "$archive_path")" "$export_path"
    xcodebuild \
      -workspace Runner.xcworkspace \
      -scheme Runner \
      -configuration Profile \
      -archivePath "$archive_path" \
      -allowProvisioningUpdates \
      DEVELOPMENT_TEAM="$IOS_TEAM_ID" \
      archive
    xcodebuild -exportArchive \
      -archivePath "$archive_path" \
      -exportPath "$export_path" \
      -exportOptionsPlist "$export_plist" \
      -allowProvisioningUpdates
  ) && build_ok=1 || build_ok=0

  mv -f "$pb_bak" "$pb"
  rm -f "$export_plist"

  if [[ "$build_ok" -ne 1 ]]; then
    echo "✗ iOS Profile archive/export failed" >&2
    exit 1
  fi

  local ipa
  ipa="$(find "$export_path" -maxdepth 1 -name '*.ipa' | head -1)"
  if [[ -z "$ipa" ]]; then
    echo "✗ No IPA in $export_path" >&2
    exit 1
  fi
  cp -f "$ipa" "$DIST_DIR/finamp-ios-profile.ipa"
  echo "✓ $DIST_DIR/finamp-ios-profile.ipa"
}

write_manifests() {
  parse_pubspec_version
  local apk="$DIST_DIR/finamp-android-profile.apk"
  local ipa="$DIST_DIR/finamp-ios-profile.ipa"
  local apk_sha="" ipa_sha="" apk_size=0 ipa_size=0
  local base_url="https://github.com/${REPO}/releases/download/${FLOATING_TAG}"
  local published
  published="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

  if [[ -f "$apk" ]]; then
    apk_sha="$(sha256_file "$apk")"
    apk_size="$(wc -c <"$apk" | tr -d ' ')"
  fi
  if [[ -f "$ipa" ]]; then
    ipa_sha="$(sha256_file "$ipa")"
    ipa_size="$(wc -c <"$ipa" | tr -d ' ')"
  fi

  local notes_json
  if [[ -n "$NOTES" ]]; then
    notes_json="$NOTES"
  else
    notes_json="Sideload build ${VERSION_NAME} (${VERSION_BUILD})"
  fi
  # Escape for JSON
  notes_json="${notes_json//\\/\\\\}"
  notes_json="${notes_json//\"/\\\"}"

  local ios_block
  if [[ "$ipa_size" -gt 0 && -n "$ipa_sha" ]]; then
    ios_block=$(cat <<EOF
  "ios": {
    "ipaUrl": "${base_url}/finamp-ios-profile.ipa",
    "sha256": "${ipa_sha}",
    "sizeBytes": ${ipa_size},
    "sideStoreSourceUrl": "${base_url}/sideload-source.json"
  }
EOF
)
  else
    ios_block=$(cat <<EOF
  "ios": {
    "ipaUrl": "",
    "sha256": "",
    "sizeBytes": 0
  }
EOF
)
  fi

  cat >"$DIST_DIR/latest.json" <<EOF
{
  "version": "${VERSION_NAME}",
  "build": ${VERSION_BUILD},
  "upstreamVersion": "${UPSTREAM_VERSION}",
  "publishedAt": "${published}",
  "notes": "${notes_json}",
  "android": {
    "apkUrl": "${base_url}/finamp-android-profile.apk",
    "sha256": "${apk_sha}",
    "sizeBytes": ${apk_size}
  },
${ios_block}
}
EOF

  if [[ "$ipa_size" -gt 0 && -n "$ipa_sha" ]]; then
    cat >"$DIST_DIR/sideload-source.json" <<EOF
{
  "name": "Finamp Sideload",
  "identifier": "com.anonymous.finamp.sideload",
  "sourceURL": "${base_url}/sideload-source.json",
  "apps": [
    {
      "name": "Finamp",
      "bundleIdentifier": "${IOS_BUNDLE_ID}",
      "developerName": "Sideload",
      "versions": [
        {
          "version": "${VERSION_NAME}",
          "buildVersion": "${VERSION_BUILD}",
          "date": "${published}",
          "localizedDescription": "${notes_json}",
          "downloadURL": "${base_url}/finamp-ios-profile.ipa",
          "size": ${ipa_size}
        }
      ]
    }
  ]
}
EOF
  else
    cat >"$DIST_DIR/sideload-source.json" <<EOF
{
  "name": "Finamp Sideload",
  "identifier": "com.anonymous.finamp.sideload",
  "sourceURL": "${base_url}/sideload-source.json",
  "apps": []
}
EOF
    echo "⚠ No IPA in dist — SideStore source left empty; app will show USB-only instructions"
  fi
  echo "✓ Wrote $DIST_DIR/latest.json and sideload-source.json"
}

upload_github() {
  if [[ "$SKIP_UPLOAD" == "1" ]]; then
    echo "==> SKIP_UPLOAD=1 — not uploading"
    return
  fi
  if ! command -v gh >/dev/null 2>&1; then
    echo "✗ gh CLI required for upload" >&2
    exit 1
  fi
  parse_pubspec_version
  local assets=()
  [[ -f "$DIST_DIR/finamp-android-profile.apk" ]] && assets+=("$DIST_DIR/finamp-android-profile.apk")
  [[ -f "$DIST_DIR/finamp-ios-profile.ipa" ]] && assets+=("$DIST_DIR/finamp-ios-profile.ipa")
  assets+=("$DIST_DIR/latest.json" "$DIST_DIR/sideload-source.json")

  if gh release view "$GIT_TAG" --repo "$REPO" >/dev/null 2>&1; then
    echo "==> Updating existing release $GIT_TAG"
    gh release upload "$GIT_TAG" "${assets[@]}" --repo "$REPO" --clobber
  else
    echo "==> Creating release $GIT_TAG"
    gh release create "$GIT_TAG" "${assets[@]}" \
      --repo "$REPO" \
      --title "$GIT_TAG" \
      --notes "${NOTES:-Sideload OTA ${VERSION_NAME}+${VERSION_BUILD}}"
  fi

  # Floating tag/release for stable download URLs
  if gh release view "$FLOATING_TAG" --repo "$REPO" >/dev/null 2>&1; then
    echo "==> Refreshing floating release $FLOATING_TAG"
    gh release upload "$FLOATING_TAG" "${assets[@]}" --repo "$REPO" --clobber
  else
    echo "==> Creating floating release $FLOATING_TAG"
    gh release create "$FLOATING_TAG" "${assets[@]}" \
      --repo "$REPO" \
      --title "Sideload latest" \
      --notes "Floating assets for in-app OTA. Pointed at ${GIT_TAG}."
  fi
  echo "✓ Published to https://github.com/${REPO}/releases"
}

print_smoke() {
  parse_pubspec_version
  cat <<EOF

== Smoke checklist ==
1. Pixel: Settings → Updates → allow Install unknown apps; complete one-time Install if needed.
2. adb install -r dist/finamp-android-profile.apk  (bootstrap / emergency only)
3. Publish done → wait for Auto at configured time (default 3:33) or Check now.
4. iPhone: SideStore source or ./scripts/install-ios-profile.sh (no silent OTA).
5. Confirm latest.json: https://github.com/${REPO}/releases/download/${FLOATING_TAG}/latest.json
6. Keystore still backed up in Bitwarden: Finamp sideload Android keystore

Version: ${VERSION_NAME}+${VERSION_BUILD}
EOF
}

main() {
  if [[ "${BUMP:-0}" == "1" ]]; then
    bump_sideload
  fi
  parse_pubspec_version
  if [[ "$SKIP_ANDROID" != "1" ]]; then
    build_android_profile
  fi
  if [[ "$SKIP_IOS" != "1" ]]; then
    build_ios_profile
  fi
  write_manifests
  upload_github
  print_smoke
}

main "$@"
