name: Upload Assets

on:
  push:
    tags:
      - '*.*.*'

# Due to a flutter bug, flutter build is not generating localizations
# workaround by always running flutter pub get immediately before building,
# and performing build for msix:create manually to allow implementing this workaround
jobs:
  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Clone repository
  #     uses: actions/checkout@v4
  #   - uses: actions/setup-java@v4
  #     with:
  #       distribution: 'zulu'
  #       java-version: '17'
  #   - name: Install dependencies
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install -y build-essential cmake ninja-build libgtk-3-dev
  #   - name: Set up Flutter
  #     uses: subosito/flutter-action@v2
  #     with:
  #       channel: 'stable'
  #   - run: flutter doctor
  #   - run: flutter pub get
  #   - run: flutter test
  
  upload-linux:
    name: Build and Upload Linux Assets
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build libgtk-3-dev
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter doctor
    - run: flutter pub get
    - run: flutter build linux --release --no-pub
    # copy icon assets and desktop file next to bundle location for easy including in tar archive
    - run: |
        cp -r assets/icon/linux/ build/linux/x64/release/icons \
        && cp assets/finamp.desktop.m4 build/linux/x64/release/ \
        && cp assets/com.unicornsonlsd.finamp.metainfo.xml build/linux/x64/release/
    # archive bundle and generate checksum
    - run: |
        tar -czf finamp-${{ github.ref_name }}-linux-release.tar.gz --directory build/linux/x64/release/ bundle icons finamp.desktop.m4 com.unicornsonlsd.finamp.metainfo.xml \
        && sha256sum finamp-${{ github.ref_name }}-linux-release.tar.gz > finamp-${{ github.ref_name }}-linux-release.tar.gz.sha256sum
    - uses: actions/upload-artifact@v4
      with:
        name: finamp-${{ github.ref_name }}-linux-release.tar.gz
        path: finamp-${{ github.ref_name }}-linux-release.tar.gz
        compression-level: 0 # no compression
    - uses: actions/upload-artifact@v4
      with:
        name: finamp-${{ github.ref_name }}-linux-release.tar.gz.sha256sum
        path: finamp-${{ github.ref_name }}-linux-release.tar.gz.sha256sum
        compression-level: 0 # no compression
    - name: Upload release archive
      uses: alexellis/upload-assets@0.4.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./finamp-${{ github.ref_name }}-linux-release.tar.gz", "./finamp-${{ github.ref_name }}-linux-release.tar.gz.sha256sum"]'
